### PR TITLE
[Utility] Fix flaky tests `TestUtilityContext_ApplyBlock` and `TestUtilityContext_EndBlock`

### LINKED ISSUE #373: [Utility] Flaky tests (`TestUtilityContext_ApplyBlock` and `TestUtilityContext_EndBlock`)
## Objective

The tests `TestUtilityContext_ApplyBlock` and `TestUtilityContext_EndBlock` are showing flaky behaviour. 

## Origin Document

It looks like the issue went almost unnoticed for a while and was never captured in a ticket. 

### More context:

image

:arrow_left:
```bash
for i in {1..100}; do go test -timeout 2s -count=1 -run ^TestUtilityContext_ApplyBlock$ github.com/pokt-network/pocket/utility/test; done;
```
:arrow_right:
```bash
for i in {1..100}; do go test -timeout 2s -count=1 -race -run ^TestUtilityContext_ApplyBlock$ github.com/pokt-network/pocket/utility/test; done;
```

(similarly for `TestUtilityContext_EndBlock`, just replace above)

My high-level investigation points at the same code-block that was copy-pasted (it's basically identical) so it looks like a "two birds with one stone" situation.

```go
	feesAndRewardsCollectedFloat := new(big.Float).SetInt(feeBig)
	feesAndRewardsCollectedFloat.Mul(feesAndRewardsCollectedFloat, big.NewFloat(float64(proposerCutPercentage)))
	feesAndRewardsCollectedFloat.Quo(feesAndRewardsCollectedFloat, big.NewFloat(100))
	expectedProposerBalanceDifference, _ := feesAndRewardsCollectedFloat.Int(nil)
	proposerAfterBalance, err := ctx.GetAccountAmount(addrBz)
	require.NoError(t, err)

	proposerBalanceDifference := big.NewInt(0).Sub(proposerAfterBalance, proposerBeforeBalance)
	require.Equal(t, expectedProposerBalanceDifference, proposerBalanceDifference)
```	

## Goals

- [ ] Identify the root cause of the flaky behaviour
- [ ] Fix the issue(s) identified in the previous point

## Deliverable

- [ ] Updated tests

## Non-goals / Non-deliverables

- Change in the testing and/or business logic 

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- The following commands should not return any failures:
  - `for i in {1..100}; do go test -timeout 2s -count=1 -run ^TestUtilityContext_ApplyBlock$ github.com/pokt-network/pocket/utility/test; done;`
  - `for i in {1..100}; do go test -timeout 2s -count=1 -race -run ^TestUtilityContext_ApplyBlock$ github.com/pokt-network/pocket/utility/test; done;`
  - `for i in {1..100}; do go test -timeout 2s -count=1 -run ^TestUtilityContext_EndBlock$ github.com/pokt-network/pocket/utility/test; done;`
  - `for i in {1..100}; do go test -timeout 2s -count=1 -race -run ^TestUtilityContext_EndBlock$ github.com/pokt-network/pocket/utility/test; done;`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk

### PR DESCRIPTION
**Pull request by Olshansk**
## Description

Fix a flaky unit test in the utility module and address a bit of tech debt in parallel.

## Issue

Fixes #373

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [x] Bug fix
- [x] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

**Root cause of bug:**
- In `newTestingTransaction`, always make the recipient a random address. This avoids the situation where the `proposer` and the `recipient` are the same (unlike but possible) resulting in the balance being increment in two different ways.

**Code cleanup:**
- Change order of params in `getActorByAddr`
- Avoid a few places with redundant byte <> string conversions
- Move tests from `block_test.go` that belong in `actor_test.go`
- Use more semantic variable naming where appropriate
- Use the `getFirstActor` helper test function in a few places
- Remove incorrect comments

## Testing

- [x] `for i in {1..100}; do go test -timeout 2s -count=1 -run ^TestUtilityContext_ApplyBlock$ github.com/pokt-network/pocket/utility/test; done; `
- [x] `make develop_test`
- [x] `make test_utility`
- [ ] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested my changes using the available tooling
- [ ] I have updated the corresponding CHANGELOG

### If Applicable Checklist
- [ ] I have updated the corresponding README(s); local and/or global
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

### CODE REVIEW

File: utility/test/actor_test.go [hunk 1]
```diff
@@ -602,14 +606,10 @@ func getFirstActor(t *testing.T, ctx utility.UtilityContext, actorType typesUtil
...
-func getActorByAddr(t *testing.T, ctx utility.UtilityContext, addr []byte, actorType typesUtil.ActorType) (actor modules.Actor) {
+func getActorByAddr(t *testing.T, ctx utility.UtilityContext, actorType typesUtil.ActorType, addr string) (actor modules.Actor) {
 	actors := getAllTestingActors(t, ctx, actorType)
-	for _, a := range actors {
-		if a.GetAddress() == hex.EncodeToString(addr) {
-			return a
-		}
-	}
-	return
+	idx := slices.IndexFunc(actors, func(a modules.Actor) bool { return a.GetAddress() == addr })
```
Comment (deblasis) [inline utility/test/actor_test.go:611]: very nice

**Review by deblasis — APPROVED** [review]
@Olshansk wearing the forensic accountant hat:

image

you should take a look at FT....nevermind :P

LGTM 🚢

File: utility/test/actor_test.go (hunk 1 above)
Comment (Olshansk) [reply utility/test/actor_test.go:611]: Thought you'd notice this one :)
