### PR TITLE
[P2P] fix: raintree add/remove index

### LINKED ISSUE #617: [P2P] Raintree address index search bug
## Objective

Fix a bug in the raintree implementation and make tests sensitive to regression.

## Origin Document

image

image

## Goals

- Improve test coverage of the raintree implementation
- Improve correctness of the raintree implementation

## Deliverable

- [ ] Add regressions test(s) (i.e. fails on `main` pre-merge) which assert that each address is seen once as a routing target 
- [ ] Add "alphabet" test(s) (see: `p2p/raintree/peers_manager_test.go`) to make sure that add/remove preserve the ring-like structure
- [ ] Add "alphabet" test(s) which have offset `addrList`s (i.e. doesn't start with `A`) and asserts that each address would be contacted
- [ ] Update the address list binary search to split the list where the sort "wraps around" to search each separately

## Non-goals / Non-deliverables

- Refactoring un-related P2P module package members

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @deblasis @Olshansk

### PR DESCRIPTION
**Pull request by bryanchriswhite**
## Description

Fixes the index at which `sortedPeersView#Add()` and `#Remove()` operates and adds a regression test.

## Issue

Fixes #617 

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Add test to assert peers view addresses order using alphabet addresses (single letters) for convenience.
- Fixes the sorted addresses index bug
- Fixes peerstore benchmarks

## Testing

- [x] `make develop_test`; if any code changes were made
- [ ] [Docker Compose LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md); if any major functionality was changed or introduced
- [x] [k8s LocalNet](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md); if any infrastructure or configuration changes were made

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [x] I have tested my changes using the available tooling
- [x] I have updated the corresponding CHANGELOG

### If Applicable Checklist

- [ ] I have updated the corresponding README(s); local and/or global
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

### CODE REVIEW

**Comment by deblasis** [comment]
Not sure if it should be tackled here or in a separate issue but:
- `make benchmark_p2p_addrbook` fails on this branch because of missing mocks configuration 
>host.go:55: Unexpected call to *mock_types.MockHost.Peerstore([]) at /home/alex/CODE/OSS/pocket2/p2p/utils/host.go:55 because: there are no expected calls of the method "Peerstore" for that receiver
- `make benchmark_p2p_addrbook` fails on `main` at this assertion: 
https://github.com/pokt-network/pocket/blob/760ee2fc07805a071d3dbb6f3aa67b06e0b34e30/p2p/raintree/peers_manager_test.go#L166

Just flagging, I am gonna proceed with the review, this was literally the first test I ran :)

File: p2p/types/peers_view.go [hunk 1]
```diff
@@ -113,3 +114,20 @@ func (view *sortedPeersView) sortAddrs(startAddr crypto.Address) {
...
+// or at which to insert it if not present.
+func (view *sortedPeersView) getAddrIndex(addr crypto.Address) int {
+	wrapIdx := sort.Search(len(view.sortedAddrs), func(visitIdx int) bool {
+		return view.sortedAddrs[visitIdx] < view.sortedAddrs[0]
+	})
+
+	frontAddrs := view.sortedAddrs[:wrapIdx]
+	backAddrs := view.sortedAddrs[wrapIdx:]
+	i := sort.SearchStrings(frontAddrs, addr.String())
+	if i == 0 {
```
Comment (deblasis) [inline p2p/types/peers_view.go:128]: Here I would add a simple comment explaining the "why" of this.
At a glance, I am a bit confused because I remember that `SearchString` returns `len(a)` when something is not found and that's, generally speaking, the most common check that's done after searching for a needle in a haystack.

Wdyt?

File: p2p/types/peers_view_test.go [hunk 2]
```diff
@@ -1,9 +1,123 @@
...
+		removeAddrs   string
+		expectedAddrs string
+	}{
+		{
+			"highest self address",
+			"A",
+			"BC",
+			"",
+			"ABC",
+		},
```
Comment (deblasis) [inline p2p/types/peers_view_test.go:26]: I understand that cool people don't use VSCode but other editors that show a "hint" about the name of the variables from the context. :)

That said, I don't have a strong opinion, feel free to ignore completely but I would consider making the test cases definitions more verbose, I bothered writing this just because all the arguments are strings. This way I don't have to scroll and read what is argument at index 2 if that makes sense.

Something like this (and below): 

```suggestion
		{
			name:          "highest self address",
			selfAddr:      "A",
			addAddrs:      "BC",
			removeAddrs:   "",
			expectedAddrs: "ABC",
		},
```

If it sounds overkill, I get it. Ignore.

Comment (bryanchriswhite) [reply p2p/types/peers_view_test.go:26]: Great suggestion :100: , thank you for making me aware of this! :eyes:

File: p2p/types/peers_view.go (hunk 1 above)
Comment (bryanchriswhite) [reply p2p/types/peers_view.go:128]: :100: perfect suggestion - thank you! :raised_hands: 

You're correct about `SearchString()`s return value, in context, index `0` means "before the self addr". In that case we need to consider `backAddrs` because, by definition, all of its values are "smaller" than self addr.
_(mostly writing this for myself to work out how to phrase the comment - suggestions are welcome :stuck_out_tongue_closed_eyes:)_

File: p2p/types/peers_view_test.go (hunk 2 above)
Comment (Olshansk) [reply p2p/types/peers_view_test.go:26]: > I understand that cool people don't use VSCode but other editors that show a "hint" about the name of the variables from the context. :)

On the contrary: cool people DO use VSCode.

But, I do support this change!

File: p2p/types/peers_view.go [hunk 3]
```diff
@@ -113,3 +114,20 @@ func (view *sortedPeersView) sortAddrs(startAddr crypto.Address) {
 	}
 	view.sortedAddrs = append(view.sortedAddrs[i:len(view.sortedAddrs)], view.sortedAddrs[0:i]...)
 }
+
+// getAddrIndex returns the sortedAddrs index at which the given address is stored
+// or at which to insert it if not present.
+func (view *sortedPeersView) getAddrIndex(addr crypto.Address) int {
+	wrapIdx := sort.Search(len(view.sortedAddrs), func(visitIdx int) bool {
```
Comment (Olshansk) [inline p2p/types/peers_view.go:121]: Can you add a comment of what this sort.Search does?

File: p2p/types/peers_view_test.go [hunk 4]
```diff
@@ -1,9 +1,123 @@
...
+func TestSortedPeersView_Add_Remove(t *testing.T) {
+	testCases := []struct {
+		name          string
+		selfAddr      string
+		addAddrs      string
+		removeAddrs   string
+		expectedAddrs string
+	}{
+		{
+			"highest self address",
```
Comment (Olshansk) [inline p2p/types/peers_view_test.go:21]: Should this be `lowest` (and the next one `highest`)?

**Review by Olshansk — CHANGES_REQUESTED** [review]
A couple nits and +1 to the comments from @deblasis

File: p2p/types/peers_view_test.go (hunk 4 above)
Comment (bryanchriswhite) [reply p2p/types/peers_view_test.go:21]: Nice catch - thanks! :raised_hands:

File: p2p/types/peers_view_test.go [hunk 5]
```diff
@@ -105,6 +103,62 @@ func TestSortedPeersView_Remove(t *testing.T) {
...
+			initialAddrs:      "BDCEA",
+			expectedSortOrder: "CDEAB",
+		},
+	}
+	for _, testCase := range testCases {
+		t.Run(testCase.name, func(t *testing.T) {
+			selfAddr := cryptoPocket.Address(testCase.selfAddr)
+
+			pstore := make(PeerAddrMap)
+			var initialPeers []Peer
```
Comment (Olshansk) [inline p2p/types/peers_view_test.go:137]: Confirming that this works?

Screenshot 2023-04-14 at 1 48 19 PM

**Review by Olshansk — APPROVED** [review]
Appreciate the comments! Just left one comment where ChatGPT was probably wrong but I didn't test it out myself.

If the unit tests pass, :shipit:

File: p2p/types/peers_view_test.go (hunk 5 above)
Comment (bryanchriswhite) [reply p2p/types/peers_view_test.go:137]: I don't recall thinking about this when writing it but it's a good distinction to make and one that seems easy to miss. In this case it doesn't matter because despite being nil initially, it is still a valid argument to the `append()` built-in, which does what you would expect.
