### PR TITLE
[CLI][Localnet][Bug] - [localnet_client_debug] Error 137 - Issue #607

### LINKED ISSUE #607: [CLI][Localnet][Bug] - [localnet_client_debug] Error 137
## Objective

Currently, the debug keybase is rehydrated from the `private_keys.yaml` that is embedded in the binary if it's built with the "debug" build tag.

It works but it means that the rehydration process has to be performed every time the local keybase is emptied and that can happen a lot especially when developing with quick feedback loops in localnet with lots of `make localnet_down` followed by `localnet_up`.

We should improve this because it causes frustrations and slows down development.

## Origin Document

Multiple conversations and first-hand experience. Just a fresh example:

image

I am also still experiencing random:  
```
{"level":"debug","time":"2023-03-17T18:51:00Z","message":"Debug keybase initializing... Adding 999 validator keys to the keybase"}
command terminated with exit code 137
make: *** [localnet_client_debug] Error 137
```

## Goals

- Optimize the process 

## Deliverable

- [ ] Updated codebase

## Non-goals / Non-deliverables

- Logic updates

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] Videos showing the improvement
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @gokutheengineer, @okdas

### PR DESCRIPTION
**Pull request by deblasis**
## Description

This PR improves the keybase initialization by:
- doing the work only if the `private_keys.yaml` has been changed 
- creating a backup of the keybase
- loading it (which is way cheaper than parsing the yaml and rehydrating the keybase from scratch) 

### Before

At 1:46 I run `make localnet_client_debug` and you can see it takes a long time plus it's a very expensive operation

https://user-images.githubusercontent.com/29378614/227202479-1320fdf4-f851-4a58-884e-a36b3c385b84.mp4

### After

At 1:12 I run `make localnet_client_debug` and it's basically instantaneous with no further spikes in CPU/RAM usage

https://user-images.githubusercontent.com/29378614/227202494-a1eff819-e2d9-4881-a2e5-4b28448d574c.mp4

Where is the magic? 
We do the expensive operation only when needed and that means when the `private_keys.yaml` has changed.

This is handled by a small binary that calculates the hash of the yaml file, compares it with the one we have already (if any) and if needed, it recreates a backup of the keybase that can be rehydrated from the debug client.

Sloppy recording but it shows the whole process:

https://user-images.githubusercontent.com/29378614/227204654-7b7f3ea8-6db5-473c-ac6c-75be13f60553.mp4

## Issue

Fixes #607 

## Type of change

Please mark the relevant option(s):

- [x] New feature, functionality or library
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Updated debug keybase initialization
- Created small binary to help with the integrity check

## Testing

- [x] `make develop_test`
- [x] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [x] I have tested my changes using the available tooling
- [x] I have updated the corresponding CHANGELOG

### If Applicable Checklist

- [ ] I have updated the corresponding README(s); local and/or global
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

### CODE REVIEW

**Comment by deblasis** [comment]
@0xBigBoss and @h5law , I am not tagging you guys as reviewers because I don't want to assume that you want to spend time on this at all but if you are curious, I have made some changes to improve the keybase initialization process.

File: app/client/keybase/debug/keystore.go [hunk 1]
```diff
@@ -45,81 +36,17 @@ func init() {
...
 	kb, err := keybase.NewKeybase(debugKeybasePath)
 	if err != nil {
 		return err
 	}
 	db := kb.GetBadgerDB()
 
-	// Add the keys if the keybase contains less than 999
-	curAddr, _, err := kb.GetAll()
-	if err != nil {
+	if err := restoreBadgerDB(build.DebugKeybaseBackup, db); err != nil {
```
Comment (h5law) [inline app/client/keybase/debug/keystore.go:46]: This logic is much cleaner 10/10  🚀

File: build/debug_keybase/main.go [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+	}
+	sourceYamlPath := os.Args[1]
+	targetFolderPath := os.Args[2]
+
+	privateKeysYamlBytes, err := ioutil.ReadFile(sourceYamlPath)
+	if err != nil {
+		fmt.Printf("Error reading source_yaml: %v\n", err)
+		return
+	}
+	sourceYamlHash := md5.Sum(privateKeysYamlBytes)
```
Comment (h5law) [inline build/debug_keybase/main.go:40]:
```suggestion
	sourceYamlHash := md5.Sum(privateKeysYamlBytes) // nolint:gosec Weak hashing function only used to check if the file has been changed
```

Just to avoid the linter error here

File: build/debug_keybase/main.go [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+	hashString := fmt.Sprintf("%x.md5", sourceYamlHash)
+	hashFilePath := filepath.Join(targetFolderPath, hashString)
+	targetFilePath := filepath.Join(targetFolderPath, "debug_keybase.bak")
+	_, err = os.Stat(hashFilePath)
```
Comment (h5law) [inline build/debug_keybase/main.go:44]: Not completely necissary but we have the function `FileExists` in `shared/utils/file_utils.go`

```go
// Check file at the given path exists
func FileExists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if errors.Is(err, fs.ErrNotExist) {
		return false, nil
	}
	return false, err
}
```

If you don't decide to change to use this see the comment below

**Review by h5law — APPROVED** [review]
@deblasis This is great. I was concerned about the time it took to load the keys even with the use of `WriteBatch` this is such a great improvement. I left two minor comments but overall everything looks great as usual with your work!

PS. Love the emojis in the print lines 👀

File: build/debug_keybase/main.go (hunk 3 above)
Comment (deblasis) [reply build/debug_keybase/main.go:44]: This is great! Thanks for pointing that out:

Much better
image

🙏

**Comment by deblasis** [comment]
@h5law 
> @deblasis This is great. I was concerned about the time it took to load the keys even with the use of `WriteBatch` this is such a great improvement. I left two minor comments but overall everything looks great as usual with your work!
> 
> PS. Love the emojis in the print lines 👀

You are too kind, sir, thank you very much. I have applied your suggestions 🙏

**Comment by deblasis** [comment]
@okdas 

> Oh, that long re-hydration is annoying, I agree. In https://github.com/pokt-network/pocket/pull/591#issuecomment-1474483446 @0xBigBoss suggested to reuse the volume with already imported keys which would require to import keys only once. Still, your change makes it even better!

Mounting a volume also works I guess. Code can always be changed/improved. I needed a solution fast and this the fastest thing I could come up with. 

> How do you feel about committing a binary file into the repo? I usually try to avoid this but in that case I can't think of a better way to handle this and avoid storing a binary in git.

Fair point, I thought about it but personally I think it's a trade-off worth taking considering the improved DevX. 

Of course I might be wrong.

**Comment by 0xBigBoss** [comment]
@deblasis looks great! I agree with @okdas that adding a binary to the repo "feels" like the wrong approach, but for a speed up this fast for only half a mb, i'm in.

File: app/client/keybase/debug/keystore.go [hunk 4]
```diff
@@ -128,24 +55,31 @@ func initializeDebugKeybase() error {
 	return nil
 }
 
-// parseValidatorPrivateKeysFromEmbeddedYaml fetches the validator private keys from the embedded build/localnet/manifests/private-keys.yaml manifest file.
-func parseValidatorPrivateKeysFromEmbeddedYaml() (map[string]string, error) {
+func restoreBadgerDB(backupData []byte, db *badger.DB) error {
+	logger.Global.Debug().Msgf(fmt.Sprintf("Debug keybase initializing... Restoring from the embedded backup file..."))
```
Comment (Olshansk) [inline app/client/keybase/debug/keystore.go:59]:
```suggestion
	logger.Global.Debug().Msgf("Debug keybase initializing... Restoring from the embedded backup file...")
```

File: build/debug_keybase/main.go [hunk 5]
```diff
@@ -0,0 +1,197 @@
...
+
+	// Increasing this number is linearly proportional to the amount of RAM required for the debug client to start and import
+	// pre-generated keys into the keybase. Beware that might cause OOM and process can exit with 137 status code.
+	// 4 threads takes 350-400MiB from a few tests which sounds acceptable.
+	debugKeybaseImportConcurrencyLimit = 4
+)
+
+func main() {
+	if len(os.Args) < 3 {
+		fmt.Println("Usage: go run main.go <source_yaml> <target_folder>")
```
Comment (Olshansk) [inline build/debug_keybase/main.go:29]: `global.logger.Fatal()` ? 

Ditto elsewhere

File: build/debug_keybase/main.go [hunk 6]
```diff
@@ -0,0 +1,197 @@
...
+
+func createHashFile(hashFilePath string) {
+	fmt.Printf("🔖 Creating the MD5 hash file used to track consistency: %s\n", hashFilePath)
+
+	file, err := os.Create(hashFilePath)
+	if err != nil {
+		panic(err)
+	}
+	defer file.Close()
+	if _, err := file.WriteString("This file is used to check if the keybase dump is in sync with the YAML file. Its name is the MD5 hash of the private_keys.yaml"); err != nil {
```
Comment (Olshansk) [inline build/debug_keybase/main.go:194]: I ❤️  this pattern: the name being the hash and the content being the semantic explanation.

💯

File: build/debug_keybase/main.go [hunk 7]
```diff
@@ -0,0 +1,197 @@
...
+	targetFolderPath := os.Args[2]
+
+	privateKeysYamlBytes, err := os.ReadFile(sourceYamlPath)
+	if err != nil {
+		fmt.Printf("Error reading source_yaml: %v\n", err)
+		return
+	}
+	sourceYamlHash := md5.Sum(privateKeysYamlBytes) // nolint:gosec // Weak hashing function only used to check if the file has been changed
+	hashString := fmt.Sprintf("%x.md5", sourceYamlHash)
+	hashFilePath := filepath.Join(targetFolderPath, hashString)
```
Comment (Olshansk) [inline build/debug_keybase/main.go:42]:
```suggestion
	hashFilePath := filepath.Join(targetFolderPath, hashString) // the file name is a hash used to track changes in the keybase
```

**Review by Olshansk — APPROVED** [review]
🙌

File: build/debug_keybase/main.go (hunk 5 above)
Comment (deblasis) [reply build/debug_keybase/main.go:29]: I disagree. This is something that's either ran by a human or by a pipeline, stdout and stderr are the way IMHO.

**Comment by deblasis** [comment]
@Olshansk I didn't merge it because of this https://github.com/pokt-network/pocket/pull/608#discussion_r1147323566

Please let me know your thoughts about that.

**Comment by Olshansk** [comment]
@deblasis :shipit:
