### PR TITLE
[Infra][P2P] Bug: "address not found in peerstore" error in localnet_debug_client when scaling up Localnet - Issue #604

### LINKED ISSUE #604: [Infra][P2P] Bug: "address not found in peerstore" error in `localnet_debug_client` when scaling up Localnet
## Objective

Make sure that scaling up Localnet doesn't crash `localnet_debug_client`

## Origin Document

image

## Goals

- It shouldn't be necessary to restart manually the localnet client, it should just work out of the box

## Deliverable

- [ ] updated CLI to fix the issue
- [ ] updated P2P code to fix the issue

## Non-goals / Non-deliverables

- Logic changes

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @gokutheengineer, @okdas

### LINKED ISSUE #605: [Infra][P2P] Bug: "Error getting pstore" error in localnet_debug_client when scaling down Localnet
## Objective

Make sure that scaling down Localnet doesn't crash `localnet_debug_client`.

## Origin Document

image

## Goals

- The client currently is "stuck" in this scenario because it can trigger a consensus round and the address book it's receiving still includes the validator that was removed but that consensus still has to unstake. This should not happen.

## Deliverable

- [ ] Updated CLI to fix the issue

## Non-goals / Non-deliverables

- Logic changes

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Short video to prove the fix**:
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis
**Co-Owners**: @gokutheengineer

### PR DESCRIPTION
**Pull request by deblasis**
## Description

With the introduction of Localnet, our network is now dynamic. That means that peers can experience churn and might be offline when the sender expects them to be online.

We weren't catering for these more "advanced" scenarios and this PR tends to address some of the basic issues.

Also, it addresses the fact that the debug CLI was not updating its own peerstore because it wasn't tracking the changes in the validator set.

### Demo (also it shows how the `cluster-manager` stakes/unstakes validators...

TL;DWatch: the client doesn't crash anymore

https://user-images.githubusercontent.com/29378614/227383203-3919b14b-a6ef-4b93-8278-ce6c9cd02bb2.mp4

## Issue

Fixes #604 
Fixes #605

## Type of change

Please mark the relevant option(s):

- [ ] New feature, functionality or library
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- The debug CLI now tracks changes reusing the same logic used by validators
- Converted some of the fatal errors into recoverable ones
- Added some more logging context that was previously missed

## Testing

- [x] `make develop_test`
- [x] [LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md) w/ all of the steps outlined in the `README`
- [x] Demo video

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [x] I have tested my changes using the available tooling
- [x] I have updated the corresponding CHANGELOG

### If Applicable Checklist

- [x] I have updated the corresponding README(s); local and/or global
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Olshansk — CHANGES_REQUESTED** [review]

**Comment by Olshansk** [comment]
Also, big fan of what you were going for with `TL;DWatch`, but I think we should rebrand it to `TL;JW`: `Too Long; Just Watch`

**Comment by deblasis** [comment]
> Also, big fan of what you were going for with `TL;DWatch`, but I think we should rebrand it to `TL;JW`: `Too Long; Just Watch`

LOL, that was on purpose, the video was too long and I didn't edit it. I was basically trying to say: trust me, it works but here's the long boring uncut video if you have time :)

Definitely `TL;JW` is waaaay better. 

RebrandAllTheThings.gif ! :)

File: p2p/providers/peerstore_provider/peerstore_provider.go [hunk 1]
```diff
@@ -29,7 +29,10 @@ func ActorsToPeerstore(abp PeerstoreProvider, actors []*coreTypes.Actor) (pstore
 	pstore = make(sharedP2P.PeerAddrMap)
 	for _, a := range actors {
 		networkPeer, err := ActorToPeer(abp, a)
-		if err != nil {
+		if _, ok := err.(*ErrResolvingAddr); ok {
+			logger.Global.Warn().Err(err).Msg("ignoring ErrResolvingAddr - peer unreachable, not adding it to peerstore")
+			continue
+		} else if err != nil {
```
Comment (bryanchriswhite) [inline p2p/providers/peerstore_provider/peerstore_provider.go:35]: @Olshansk @deblasis wdyt about a `// TECHDEBT(#519)` comment here. This looks to me like a place where we may be better served in the long run by asserting for behavior rather than type (i.e. asserting against an interface type -  see Dave Cheney clip):

- image
- “Don’t just check errors, handle them gracefully”  — Dave Cheney (2016): [https://www.youtube.com/watch?v=lsBF58Q-DnY&list=WL&index=7](https://www.youtube.com/watch?v=lsBF58Q-DnY&list=WL&index=7)
- Other example of sentinel errors being problematic  (`context` context): stdlib contexts: https://share.snipd.com/chapter/7620f9f8-0a3d-41fa-8118-01663a51cb40

File: app/client/cli/debug.go [hunk 2]
```diff
@@ -258,7 +258,7 @@ func sendDebugMessage(cmd *cobra.Command, debugMsg *messaging.DebugMessage) {
 	}
 
 	if err := p2pMod.Send(validatorAddress, anyProto); err != nil {
-		logger.Global.Fatal().Err(err).Msg("Failed to send debug message")
+		logger.Global.Error().Err(err).Msg("Failed to send debug message")
```
Comment (bryanchriswhite) [inline app/client/cli/debug.go:261]: Thank you! :100:

File: app/client/cli/debug.go [hunk 3]
```diff
@@ -243,7 +243,7 @@ func sendDebugMessage(cmd *cobra.Command, debugMsg *messaging.DebugMessage) {
 
 	pstore, err := fetchPeerstore(cmd)
 	if err != nil {
-		logger.Global.Fatal().Msg("Unable to retrieve the pstore")
+		logger.Global.Fatal().Err(err).Msg("Unable to retrieve the pstore")
```
Comment (bryanchriswhite) [inline app/client/cli/debug.go:246]: Thank you! :100:

File: app/client/cli/debug.go [hunk 4]
```diff
@@ -220,15 +220,15 @@ func broadcastDebugMessage(cmd *cobra.Command, debugMsg *messaging.DebugMessage)
...
 	}
 	for _, val := range pstore.GetPeerList() {
 		addr := val.GetAddress()
 		if err != nil {
 			logger.Global.Fatal().Err(err).Msg("Failed to convert validator address into pocketCrypto.Address")
 		}
 		if err := p2pMod.Send(addr, anyProto); err != nil {
-			logger.Global.Fatal().Err(err).Msg("Failed to send debug message")
+			logger.Global.Error().Err(err).Msg("Failed to send debug message")
```
Comment (bryanchriswhite) [inline app/client/cli/debug.go:231]: Thank you! :100:

File: p2p/providers/peerstore_provider/peerstore_provider.go (hunk 1 above)
Comment (deblasis) [reply p2p/providers/peerstore_provider/peerstore_provider.go:36]: Thanks @bryanchriswhite! https://github.com/pokt-network/pocket/pull/611/commits/0f40d94f37ccbc8fe52423fa815b0e4b42538464

**Review by Olshansk — APPROVED** [review]
